name: GitHub Action Demo
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # copy git 仓库到虚拟机上
      - name: "Checkout codes"
        uses: actions/checkout@v1
      # 获取最新一条提交的git log
      - name: Get Git Log
        id: git_log
        uses: Edisonboy/latest-git-log-action@main
        with:
          tag: origin/master
      # 发送邮件
      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.qq.com
          server_port: 465
          username: 1135376511@qq.com
          password: hwenrvppitdiiigj
          subject: Github Actions job result
          to: 1135376511@qq.com
          from: GitHub Actions
          body: "111"
